### ISSUE TITLE
Game Rules

### ISSUE THREAD

**Issue by KLIMaka** [SendCroissant/assault#2]
- [x] Карта для двух игроков
- [x] Выбор героев ограничен одним (одинаковый с обеих сторон)
- [x] Задизейблить автоатаку
- [x] Добавить скилл - лип
- [x] Убрать золото/магазины
- [x] Убрать резисты для того, чтобы оружие наносило именно тот дамаг, который написан
- [x] Убрать опыт и повышение уровня

**Comment by SendCroissant** [comment]
Опыт и повышение уровня тоже убрать, я так понимаю?

**Comment by KLIMaka** [comment]
> Опыт и повышение уровня тоже убрать, я так понимаю?

Да, и это тоже
