### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by KLIMaka** [SendCroissant/assault#4]
Нужны картинки для:
- [x] привью самого мода
- [x] иконки оружия
- [x] иконку липа?

**Comment by ArtiChevski** [comment]
![Leap icon](/http://i.imgur.com/uE9CLYa.png)

**Comment by ArtiChevski** [comment]
![Wavegun](http://i.imgur.com/i86azp8.png)

**Comment by ArtiChevski** [comment]
![rocket launcher](http://i.imgur.com/haDHfPA.png)

**Comment by ArtiChevski** [comment]
![shockgun](http://i.imgur.com/Es0PG5O.png)
Shock gun

**Comment by ArtiChevski** [comment]
![shotgun](http://i.imgur.com/OARQkjp.png)
Shot gun

**Comment by ArtiChevski** [comment]
Dodge еще
![dodge](http://i.imgur.com/Y1ZMc4D.png)
и еще...
![dodge](http://i.imgur.com/ZS0HufG.png)

**Comment by ArtiChevski** [comment]
![preview](http://i.imgur.com/kBex49J.png)
