### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by KLIMaka** [SendCroissant/assault#8]
Здесь складываем полезные линки

**Comment by KLIMaka** [comment]
* <a href='https://www.youtube.com/playlist?list=PLgsvKDl416GKvSjSBCUK0LVqWJi97KaRn'> making of Curse of River's End (Dota 2)</a>
* <a href='http://moddota.com/forums/discussion/14/datadriven-ability-breakdown-documentation'>DataDriven Ability Breakdown - Documentation</a>

**Comment by SendCroissant** [comment]
а почему не в вики?

**Comment by SendCroissant** [comment]
спасибо)
